### ISSUE TITLE
Set muscle excitations

### ISSUE THREAD

**Issue by fleiscse** [tgeijten/scone-core#6]
**Describe the bug**
During a simulation in sconpy, I try to set the excitation of a single muscle in order to make it contract. However, when I set the excitation, it just seems to vanish (nothing happens), and I can't see this value in any of the muscle excitation array / muscle activation array / muscle excitation / muscle activatoin / actuator input, even if I advance the simulation about a timestep. On the other hand, setting excitations using the set_actuator_inputs() does work. 

**To Reproduce**
1. load the model: model: `model  = sconepy.load_model('data/H0918_osim4.scone')`
2. reset model to initial state: `model.reset()` _[as in sconepy_example.py]_
3. Initialize the model: `model.init_state_from_dofs()` _[as in sconepy_example.py]_
4. set excitation to single muscle: `model.muscles()[0].set_excitation(1)`
5. call `model.muscles()[0].excitation()` --> will return zero
6. call _model.muscle_excitation_array()_ --> will also return zeros 

**Expected behavior**
When I set the muscle excitation for one / more muscles, I would expect to get that value returned when I call .excitation(), and to observe the activation of that muscle during the following timesteps. 

**Desktop (please complete the following information):**
 - Windows 10
 - SCONE Version 2.1.0.2621
![Screenshot2](https://github.com/tgeijten/scone-core/assets/84860444/885807bc-a455-44c7-8c8d-ebc56bad470a)

![Screenshot1](https://github.com/tgeijten/scone-core/assets/84860444/25e070a8-9d5a-4efb-9651-d3d94a6ff21c)

**Comment by tgeijten** [comment]
Thank you for reporting this. The `Muscle.set_excitation()` function is from a previous iteration and is no longer supported because of performance issues. Instead, you should set the inputs for all actuators simultaneously using the `model.set_actuator_inputs()` function. If you only wish to excite a single muscle, simply set the other values to zero.

`Muscle.set_excitation()` will be removed in the next release to avoid confusion. Sorry for the inconvenience.
